%% UI Game Setup Activity Diagram
%% Last Updated: 3/18/2026
%% Version: 1.0

%% Purpose
%% To show user actions between opening the game and starting gameplay

%% Scope
%% The Game setup logic/UI

stateDiagram-v2
    [*] --> Display_Game_And_Assets
    Display_Game_And_Assets --> Choose_Name_and_Piece

    %% user block
    state "User" as User {
        Choose_Name_and_Piece --> Start_Game
        Choose_Name_and_Piece --> Learn_More
        Start_Game --> Roll_Dice
        Learn_More --> Connect_Home_Page
    }

    %%system block
    state "System" as System {
        Connect_Home_Page
        Roll_Dice --> Display_Roll
        Display_Roll --> Move_Piece
        Move_Piece --> Display_Tile

        %%divide into tile branches
        Display_Tile --> Property_Tile : property_tile?
        Display_Tile --> Action_Tile : action_tile?
        Display_Tile --> Jail_Tile : jail_tile?

        %%properry tile flow
        state Property_Tile {
            Check_Property
            Check_Property --> Pay_Rent : owned_by_other
            Check_Property --> No_Action : owned_by_user
            Check_Property --> Buy_Choice : not_owned_by_other
            Buy_Choice --> Purchase_Property
            Buy_Choice --> No_Action
            Pay_Rent --> Update_Cash
            Purchase_Property --> Update_Cash
            No_Action --> Update_Cash
        }

        %%action tile flow
        state Action_Tile {
            Display_Event_Card
            Display_Event_Card --> Event_Outcome
            Event_Outcome --> New_Tile : go_to_tile
            Event_Outcome --> Collect_Cash : collect_cash
            Event_Outcome --> Pay_Fee : pay_fee
            Collect_Cash --> Update_Cash
            Pay_Fee --> Update_Cash
        }

        New_Tile --> Display_Tile

        %% jail flow
        state Jail_Tile {
            Display_Jail
            Display_Jail --> Simulate_Turn_Skipped
            Simulate_Turn_Skipped --> Update_Cash
        }

        %% post-turn win/loss check flow
        Update_Cash --> Win_Check
        Win_Check --> Display_Win : Cash ≥ $10,000
        Win_Check --> Lose_Check : Cash < $10,000
        Lose_Check --> Display_Lose : Cash ≤ $0
        Lose_Check --> Simulate_Opponent : Cash > $0

        Simulate_Opponent --> Show_Opponent_Turn
        Show_Opponent_Turn --> Roll_Dice
    }

    %% win//loss sttes
    Display_Win --> [*]
    Display_Lose --> [*]
