stateDiagram-v2
  direction LR
  [*] --> Free

  Free --> InJail : GoToJail / jailCounter=0

  InJail --> AwaitTurn

  AwaitTurn --> AttemptEscape : jailCounter++
  AwaitTurn --> PayFee : Pay $150
  AwaitTurn --> UseCard : Use GetOutOfJailFree (only on 1st turn)

  AttemptEscape --> Released : RollDoubles / MoveExitRollAgain
  AttemptEscape --> AwaitTurn : NoDoubles / StayInJail
  AttemptEscape --> ForcedExit : jailCounter == 3 / ForcePay
  ForcedExit --> PayFee

  PayFee --> Released : ExitAfterPayment
  UseCard --> Released : ExitAfterCard
  ForcedExit --> Released : ExitAfterForcedPay


  Released --> Free : ResumeNormalTurn / Roll

  note right of InJail
    Rules: [1] Up to 3 rolls allowed to attempt doubles [2] Pay $150 anytime to exit [3] Use card only on first attempt [4] Forced to pay $100 after 3 failed rolls
  end note
