%% System State Diagram
%% Last Updated: 3/18/2026
%% Version: 1.0

%% Purpose
%% To show the different states the game can be in while the core game loop is executing

%% Scope
%% The entire system 

stateDiagram-v2
    [*] --> None

    %%initialization
    None --> Initializing : start_game()
    Initializing --> WaitingForTurn : setup_complete()

    %% primary game loop; can restart from game over
    WaitingForTurn --> PlayerTurn : player_turn_start()

    PlayerTurn --> BotTurn : end_player_turn()
    PlayerTurn --> GameOver : player_bankrupt()

    BotTurn --> WaitingForTurn : end_bot_turn()
    BotTurn --> GameOver : bot_bankrupt()

    %%again, can either start a new game OR exit
    GameOver --> Initializing : restart_game()
    GameOver --> [*] : exit_game()

    %% generall notes for each action to avoid having long names
    note right of Initializing
        System loads assets, creates players,
        initializes board/variables
    end note

    note right of WaitingForTurn
        Player waits for their turn
    end note

    note right of PlayerTurn
        Player rolls dice, info is displayed to
        user.
    end note

    note right of BotTurn
        Opponent AI simulates actions,
        modifies game state.
    end note

    note right of GameOver
        Evaluates win/loss condition:
        - Win: cash ≥ $10,000
        - Lose: bankrupt (cash ≤ 0)
        Returns to Initializing on restart,
        OR user can exit game.
    end note
